<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Protocol\LocalBridge.Protocol.csproj" />
    <ProjectReference Include="..\WindowsShared\LocalBridge.WindowsShared.csproj" />
  </ItemGroup>
</Project>
