name: Semgrep

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Scan source
        run: semgrep scan --config auto --error
